
version: 2

models:
  # - name: aave_atokens
  #   description: "All aave atokens with metadata"
  #   # columns:
  #   #   - name: id
  #   #     description: "The primary key for this table"
  #   #     tests:
  #   #       - unique
  #   #       - not_null
  - name: aave_atokens
    description: "All atokens & associated metadata"

