version: 2

sources:
  - name: financials_data_lake
    tables:
      - name: market_tokens_by_day
      - name: block_numbers_by_day
      - name: tx_classification
      - name: display_names
      - name: aave_oracle_prices_by_day
      - name: streams_metadata
      - name: streaming_payments_state
      - name: non_atoken_transfers_by_day
      - name: eth_balances_by_day
  - name: protocol_data_lake
    tables:
      - name: matic_lsd_token_supply_by_day
      - name: safety_module_rpc
      - name: coingecko_data_by_day
      - name: protocol_data_by_hour
      - name: emode_config_by_day
      - name: compound_v2_by_hour
      - name: compound_v3_by_hour
      - name: beacon_chain_staking_returns_by_day
      - name: compound_v2_by_day
      - name: compound_v3_by_day
      - name: safety_module_bal_pool_contents
  - name: warehouse
    tables:
      - name: atoken_measures_by_day
      - name: block_by_day
      - name: non_atoken_measures_by_day
      - name: treasury_incentives_by_day
      - name: user_rewards_by_day
      - name: balance_group_lookup
      - name: aave_internal_addresses
      - name: token_prices_by_day
      - name: market_state_by_day
      - name: market_config_by_day
      - name: incentives_by_day
      - name: liquidity_depth
      - name: balancer_bpt_by_day
      - name: paraswap_legacy_claimable_fees
      