version: 2

sources:
  - name: financials_data_lake
    tables:
      - name: market_tokens_by_day
      - name: block_numbers_by_day
      - name: tx_classification
      - name: display_names
      - name: aave_oracle_prices_by_day
      - name: streams_metadata
      - name: streaming_payments_state
  - name: warehouse
    tables:
      - name: atoken_measures_by_day
      - name: block_by_day
      - name: non_atoken_measures_by_day
      - name: treasury_incentives_by_day
      - name: user_rewards_by_day
      - name: balance_group_lookup
      - name: aave_internal_addresses
      - name: token_prices_by_day
      - name: market_state_by_day
      - name: market_config_by_day
      - name: incentives_by_day
      